# Generated by Django 6.0.7 on 2026-08-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0004_categoriaimportjob'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categoria',
            name='unique_categoria_user_name',
        ),
    ]
