# Generated by Django 6.0.8 on 2026-09-17 04:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuraciones', '0007_tipocuenta_cuenta_cuentaimportjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('movement_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('key_categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='configuraciones.categoria')),
                ('key_creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='configuraciones.cuenta')),
                ('key_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='configuraciones.status')),
                ('key_updater_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_movimientos',
            },
        ),
    ]
