# Generated by Django 6.0.7 on 2026-07-28 01:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuraciones', '0002_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('key_creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='configuraciones.status')),
                ('key_updater_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sec_actions',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('key_creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='configuraciones.status')),
                ('key_updater_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sec_events',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(max_length=255, null=True, unique=True)),
                ('title', models.TextField(max_length=255, null=True)),
                ('translated_title_key', models.TextField(max_length=255, null=True)),
                ('icon', models.TextField(max_length=255, null=True)),
                ('router_to', models.TextField(max_length=255, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('key_creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key_father_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.menu')),
                ('key_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='configuraciones.status')),
                ('key_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='seguridad_%(class)s', to='configuraciones.system')),
                ('key_updater_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sec_menu',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decorator_name', models.CharField(max_length=100, unique=True)),
                ('api_url', models.CharField(max_length=100, unique=True)),
                ('module_name', models.CharField(max_length=100, unique=True)),
                ('key_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.action')),
                ('key_creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='configuraciones.status')),
                ('key_updater_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sec_permissions',
            },
        ),
        migrations.CreateModel(
            name='PermissionSystem',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.permission')),
                ('key_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='configuraciones.status')),
                ('key_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='configuraciones.system')),
                ('key_updater_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sec_permission_systems',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('key_creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='configuraciones.status')),
                ('key_updater_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sec_roles',
            },
        ),
        migrations.CreateModel(
            name='PermissionRole',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.permission')),
                ('key_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='configuraciones.status')),
                ('key_updater_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.role')),
            ],
            options={
                'db_table': 'sec_permission_roles',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.role')),
                ('key_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='configuraciones.status')),
                ('key_updater_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sec_user_roles',
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('key_creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.menu')),
                ('key_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.role')),
                ('key_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='configuraciones.status')),
                ('key_updater_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sec_role_menu',
                'constraints': [models.UniqueConstraint(fields=('key_role', 'key_menu'), name='unique_role_menu')],
            },
        ),
    ]
