# Generated by Django 6.0.7 on 2026-08-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='all_access',
            field=models.BooleanField(default=False),
        ),
    ]
