# Generated by Django 6.0.7 on 2026-08-10 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=50)),
                ('modulo', models.CharField(max_length=100)),
                ('nom_tabla', models.CharField(max_length=100)),
                ('key_record', models.CharField(max_length=64)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('key_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='historiales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'his_historial',
            },
        ),
        migrations.CreateModel(
            name='HistorialDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('columna', models.CharField(max_length=100)),
                ('dato_antiguo', models.TextField(blank=True, null=True)),
                ('dato_nuevo', models.TextField(blank=True, null=True)),
                ('key_historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='historial.historial')),
            ],
            options={
                'db_table': 'his_historial_detalle',
            },
        ),
        migrations.AddIndex(
            model_name='historial',
            index=models.Index(fields=['nom_tabla', 'key_record'], name='his_histori_nom_tab_80ef0f_idx'),
        ),
    ]
