# Generated by Django 6.0.7 on 2026-07-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nro_document',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
