# Generated by Django 6.0.7 on 2026-08-07 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def grandfather_existing_users(apps, schema_editor):
    # Cuentas creadas antes de que existiera la verificación por código (ej. "demo") no
    # pasaron nunca por ese flujo: sin este backfill quedarían trabadas en el login.
    User = apps.get_model('autenticacion', 'User')
    User.objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_user_nro_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(grandfather_existing_users, migrations.RunPython.noop),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('email_verification', 'Verificación de correo'), ('password_reset', 'Restablecimiento de contraseña')], max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_verification_codes',
                'indexes': [models.Index(fields=['user', 'purpose', 'consumed_at'], name='auth_verifi_user_id_2c18ed_idx')],
            },
        ),
    ]
